config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "orders#index"

  resources :products
  resources :orders
  resources :items
end

app/models/order.rb
# frozen_string_literal: true

require "csv"

class Order < ApplicationRecord
  has_many :items, dependent: :destroy

  DATA_CONDITION = "created_at >= ? AND created_at < ?"

  scope :today, -> { where(DATA_CONDITION, Time.now.beginning_of_day, Time.now.end_of_day) }
  scope :yesterday, -> { where(DATA_CONDITION, Time.now.ago(1.day).beginning_of_day, Time.now.ago(1.day).end_of_day) }
  scope :this_month, -> { where(DATA_CONDITION, Time.now.beginning_of_month, Time.now.end_of_month) }
  scope :previous_month, -> { where(DATA_CONDITION, Time.now.ago(1.month).beginning_of_month, Time.now.ago(1.month).end_of_month) }
  scope :this_year, -> { where(DATA_CONDITION, Time.now.beginning_of_year, Time.now.end_of_year) }
  scope :previous_year, -> { where(DATA_CONDITION, Time.now.ago(1.year).beginning_of_year, Time.now.ago(1.year).end_of_year) }

  def import(file)
    CSV.foreach(file.path, headers: true) do |row|
      items = Product.where(name: row["Prekės pavadinimas"], ean: row["EAN Kodas"]).all
      if items.count > 0
        # pakesiti !!!!
        item = items.first
      else
        item = Product.create(name: row["Prekės pavadinimas"], ean: row["EAN Kodas"])
      end

      Item.create(order_id: id, product_id: item.id, price: row["Suma su nuolaida"], amount: row["Surinktas Kiekis"], full_price: row["Kaina (vnt/kg)"])
    end
  end

  def self_pdf_import(file)
    Order.self_pdf_import(file.path, self)
  end

  def Order.self_pdf_import(file_path, order = nil)
    t = Time.now.to_i
    files = `pdftohtml -c #{file_path} /tmp/#{t}.html`
    order = order.nil? ? Order.check_file("/tmp/#{t}-1.html") : order
    puts file_path
    if files.to_s.include?("Page-2")
      order.import_nikogiri("/tmp/#{t}-1.html", 1)
      order.import_nikogiri("/tmp/#{t}-2.html", 2)
    else
      order.import_nikogiri("/tmp/#{t}-1.html")
    end

    # `rm -rf /tmp/#{t}*`
  end

  def Order.check_file(file_path)
    html_doc = File.open(file_path) { |f| Nokogiri::HTML(f) }
    ps = html_doc.css("p")
    ino=""
    ps.each_with_index { |p, index|
      if p.text.to_s.include?("UŽSAKYMO Nr.")
        ino=index
      end
    }
    Order.find_or_create_by(no: ps[ino].text.to_s.split("Nr.").last.to_s.strip)
  end

  def import_nikogiri(file_path, version = 1)
    html_doc = File.open(file_path) { |f| Nokogiri::HTML(f) }
    ps = html_doc.css("p")

    if version == 1
      iean = 44
      iname = 45
      iqt = 47
      ifprice = 48
      iprice = 49
    end
    if version == 2
      iean = 3
      iname = 4
      iqt = 6
      ifprice = 7
      iprice = 8
    end

    ean = ""
    name = ""
    qt = ""
    fprice = ""
    price = ""

    nexti = 0
    depoz = 0
    stop = 0

    l = 0
    ps.each_with_index { |p, index|
      if version == 1

        if p.text.to_s.include?("UŽSAKYMO Nr.")
          self.no = p.text.to_s.split("Nr.").last.to_s.strip
          self.save
        end
        if l == 1
          self.created_at = p.text.to_s.split("/").first.to_s.delete("DATA")
          self.save
          l=0
        end
        if p.text.to_s.include?("Prekių pristatymo data ir laikas")
          l =1
        end
      end
      if version == 2
        if p.text.to_s.include?("Jums priklauso")

          iean =index+2
          iname=index+3
          iqt =index+5
          ifprice = index+6
          iprice =index+7

        end

      end

      if depoz == 1
        if p.text.to_s.include?("Lt")
          self.depozit=p.text.to_s.delete("Lt").gsub(",", ".").to_d * 0.289620019
        else
          self.depozit = p.text.to_s.delete(" €").gsub(",", ".")
        end
        self.save
        depoz=0
      end

      if nexti == 1
        if p.text.to_s.include?("Lt")
          self.price=p.text.to_s.delete("Lt").gsub(",", ".").to_d * 0.289620019
        else
          self.price = p.text.to_s.delete(" €").gsub(",", ".")
        end

        self.save
        nexti=0
      end

      if p.text.to_s.include?("EAN Kodas")

        iean =index+11
        iname=index+12
        iqt =index+14
        ifprice = index+15
        iprice =index+16

      end
      # table +-18
      if p.text.to_s.include?("Apmokestinama") or p.text.to_s.include?("Pristatymo mokestis") or p.text.to_s.include?("Suma be PVM") or p.text.to_s.include?("SumabePVM") or p.text.to_s.include?("Prekes pristačiau:")
        stop =1
      end

      if stop == 0
        if iean == index
          i=0
          # numeris

          ean=p.text.to_s
          if ean.to_s[-1, 1].include?(",")
            iean+=1
            iname+=1
            iqt+=1
            ifprice+=1
            iprice+=1
            ean+=p.text.to_s
          else
            iean +=7
          end
          name= ""
          qt=""
          fprice=""
          price=""
          # logger.debug "ean: #{ean}--- index:#{index}--- iean:#{iean}"
        end
        if iname == index
          # numeris
          iname +=7
          name = p.text.to_s
        end
        if iqt == index
          # numeris
          iqt +=7
          qt = p.text.to_s.delete(" €")
        end
        if ifprice == index
          # numeris
          ifprice +=7
          fprice = p.text.to_s.delete(" €")
        end
        if iprice == index
          # numeris
          iprice +=7
          price = p.text.to_s.delete(" €")

          i=1
        end


        if i == 1
          items = Product.where(name: name, ean: ean).all
          if items.count > 0
            # pakesiti !!!!
            item = items.first
          else
            item = Product.create(name: name, ean: ean)
          end
          if price.include?("Lt") or fprice.include?("Lt")
            price = price.delete("Lt").gsub(",", ".").to_d * 0.289620019
            fprice = fprice.delete("Lt").gsub(",", ".").to_d * 0.289620019
          else
            price = price.gsub(",", ".")
            fprice = fprice.gsub(",", ".")
          end
          # puts price
          # puts fprice
          # puts index
          # puts '-------------------'
          it = Item.where(order_id: self.id, product_id: item.id, price: price, amount: qt.delete("vnt.").delete("kg").gsub(",", ".").to_d, full_price: fprice, created_at: self.created_at).first
          if !it
            Item.create(order_id: self.id, product_id: item.id, price: price, amount: qt.delete("vnt.").delete("kg").gsub(",", "."), full_price: fprice, created_at: self.created_at)
          end
        end


      end


      if p.text.to_s.include?("Depozitas")
        depoz=1
        stop =1
      end
      if p.text.to_s.include?("Bendra suma") or p.text.to_s.include?("SUMA su PVM")
        nexti=1
        stop =1
      end

      if p.text.to_s.include?("Su AČIŪ kortele suteikta nuolaida") and index > 0
        self.discount = p.text.to_s.delete("Su AČIŪ kortele suteikta nuolaida").delete(" €").gsub(",", ".")
        self.save
        stop =1
      end

      if p.text.to_s.include?("Prekespristačiau:") and index > 0
        self.save
        stop =1
      end

      if p.text.to_s.include?("Gauta MAXIMA pinigų už šį pirkinį") and index > 0
        self.maxima = p.text.to_s.delete("Gauta MAXIMA pinigų už šį pirkinį").delete(" €").gsub(",", ".")
        self.save
        stop =1
      end
    }
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :set_order, only: [ :show, :edit, :update, :destroy ]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.order("created_at desc").all
    @this_month = Order.this_month
    @preveus_month = Order.previous_month
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)



    respond_to do |format|
      if @order.save
      # @order.import(params[:order][:file])
      @order.self_pdf_import(params[:order][:file])


        format.html { redirect_to @order, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        @order.self_pdf_import(params[:order][:file])
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:currency, :price, :discount, :depozit, :no, :maxima, :created_at)
    end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for @order, :html => { multipart:true } do |f| %>
  <label class="block text-sm">
    <span class="text-gray-700 dark:text-gray-400">Currency</span>
    <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 ">
      <%= f.text_field :currency, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6" , placeholder: "EUR" %>
    </div>
  </label>
  <label class="block text-sm">
    <span class="text-gray-700 dark:text-gray-400">Price</span>
    <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 ">
      <%= f.text_field :price, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6" , placeholder: "EUR" %>
    </div>
  </label>
  <label class="block text-sm">
    <span class="text-gray-700 dark:text-gray-400">Discount</span>
    <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 ">
      <%= f.text_field :discount, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6" , placeholder: "EUR" %>
    </div>
  </label>
  <label class="block text-sm">
    <span class="text-gray-700 dark:text-gray-400">Depozit</span>
    <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 ">
      <%= f.text_field :depozit, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6" , placeholder: "EUR" %>
    </div>
  </label>
  <label class="block text-sm">
    <span class="text-gray-700 dark:text-gray-400">No</span>
    <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 ">
      <%= f.text_field :no, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6" , placeholder: "EUR" %>
    </div>
  </label>
  <label class="block text-sm">
    <span class="text-gray-700 dark:text-gray-400">Maxima</span>
    <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 ">
      <%= f.text_field :maxima, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6" , placeholder: "EUR" %>
    </div>
  </label>
  <label class="block text-sm">
    <span class="text-gray-700 dark:text-gray-400">Date</span>
    <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 ">
      <%= f.text_field :created_at, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6" , placeholder: "EUR" %>
    </div>
  </label>
  <label class="block text-sm">
    <span class="text-gray-700 dark:text-gray-400">File</span>
    <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 ">
      <%= f.file_field :file, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6" , placeholder: "EUR" %>
    </div>
  </label>
  <label class="block text-sm">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              orders_path, :class => 'btn btn-default' %>
  </label>
<% end %>

app/views/orders/edit.html.erb
<h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
  Edit Order
</h2>

<div class="px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800">
  <%= render 'form' %>
</div>

app/views/orders/index.html.erb
<h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
  Orders
</h2>

<%= link_to "New", new_order_path %>

<div class="grid gap-6 mb-8 md:grid-cols-2 xl:grid-cols-4">
  <%= render "shared/card", card_name: "Total", card_text: "#{@orders.calculate(:sum, :price)} € | #{@orders.count}" %>
  <%= render "shared/card", card_name: "This month", card_text: "#{@this_month.calculate(:sum, :price)} € | #{@this_month.count}" %>
  <%= render "shared/card", card_name: "Previous month", card_text: "#{@preveus_month.calculate(:sum, :price)} € | #{@preveus_month.count}" %>
</div>

<div class="w-full mb-8 overflow-hidden rounded-lg shadow-xs">
  <div class="w-full overflow-x-auto">
    <table class="w-full whitespace-no-wrap">
      <thead>
        <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
          <th class="px-4 py-3">ID</th>
          <th class="px-4 py-3">Currency</th>
          <th class="px-4 py-3">Price</th>
          <th class="px-4 py-3">Discount</th>
          <th class="px-4 py-3">Depozit</th>
          <th class="px-4 py-3">No</th>
          <th class="px-4 py-3">Maxima</th>
          <th class="px-4 py-3">Date</th>
          <th class="px-4 py-3">items</th>
          <th class="px-4 py-3">Actions</th>
        </tr>
      </thead>
      <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
        <% @orders.each do |order| %>
          <tr class="text-gray-700 dark:text-gray-400">
            <td class="px-4 py-3 text-sm"><%= link_to order.id, order_path(order) %></td>
            <td class="px-4 py-3 text-sm"><%= order.currency %></td>
            <td class="px-4 py-3 text-sm"><%= order.price %></td>
            <td class="px-4 py-3 text-sm"><%= order.discount %></td>
            <td class="px-4 py-3 text-sm"><%= order.depozit %></td>
            <td class="px-4 py-3 text-sm"><%= order.no %></td>
            <td class="px-4 py-3 text-sm"><%= order.maxima %></td>
            <td class="px-4 py-3 text-sm"><%=l order.created_at %></td>
            <td class="px-4 py-3 text-sm"><%= link_to order.items.count, items_path(:order_id=>order.id) %></td>
            <td class="px-4 py-3 text-sm">
              <div class="flex items-center space-x-4 text-sm">
                <%= link_to "Edit",
                            edit_order_path(order), :class => "flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray" %>

                            <%= link_to "Destroy",
                                        order_path(order),
                                        :method => :delete,
                                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                                        :class => "flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/orders/new.html.erb
<h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
  New Order
</h2>

<div class="px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800">
  <%= render 'form' %>
</div>

app/views/orders/show.html.erb
<h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
  Order
</h2>
<h3 class=" font-semibold text-gray-900">#<%=@order.id%></h3>

<div class="px-4 sm:px-0">
  <%= link_to t('.back', :default => t("helpers.links.back")),
                orders_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_order_path(@order), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                order_path(@order),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
</div>
<div class="mt-6 border-t border-gray-100">
  <dl class="divide-y divide-gray-100">
    <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
      <dt class="text-sm/6 font-medium text-gray-900">Currency</dt>
      <dd class="mt-1 text-sm/6 text-gray-700 sm:col-span-2 sm:mt-0"><%=@order.currency%></dd>
    </div>
    <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
      <dt class="text-sm/6 font-medium text-gray-900">Price</dt>
      <dd class="mt-1 text-sm/6 text-gray-700 sm:col-span-2 sm:mt-0"><%=@order.price%></dd>
    </div>
    <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
      <dt class="text-sm/6 font-medium text-gray-900">Discount</dt>
      <dd class="mt-1 text-sm/6 text-gray-700 sm:col-span-2 sm:mt-0"><%=@order.discount%></dd>
    </div>
    <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
      <dt class="text-sm/6 font-medium text-gray-900">Depozit</dt>
      <dd class="mt-1 text-sm/6 text-gray-700 sm:col-span-2 sm:mt-0"><%=@order.depozit%></dd>
    </div>
    <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
      <dt class="text-sm/6 font-medium text-gray-900">No</dt>
      <dd class="mt-1 text-sm/6 text-gray-700 sm:col-span-2 sm:mt-0"><%=@order.no%></dd>
    </div>
    <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
      <dt class="text-sm/6 font-medium text-gray-900">Maxima</dt>
      <dd class="mt-1 text-sm/6 text-gray-700 sm:col-span-2 sm:mt-0"><%=@order.maxima%></dd>
    </div>
  </dl>
</div>