config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "orders#index"

  resources :products
  resources :orders
  resources :items
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :set_item, only: [ :show, :edit, :update, :destroy ]

  # GET /items
  # GET /items.json
  def index
    wh = {}

    if params[:order_id] and !params[:order_id].to_s.blank?
      wh[:order_id] = params[:order_id]
    end
    if params[:product_id] and !params[:product_id].to_s.blank?
      wh[:product_id] = params[:product_id]
    end

    @items = Item.where(wh).order("created_at desc").all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:product_id, :order_id, :price, :amount, :full_price)
    end
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for @item, :html => { :class => "form-horizontal item" } do |f| %>
  <label class="block text-sm">
    <span class="text-gray-700 dark:text-gray-400">product_id</span>
    <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 ">
      <%= f.text_field :product_id, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6" , placeholder: "EUR" %>
    </div>
  </label>
  <label class="block text-sm">
    <span class="text-gray-700 dark:text-gray-400">order_id</span>
    <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 ">
      <%= f.text_field :order_id, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6" , placeholder: "EUR" %>
    </div>
  </label>
  <label class="block text-sm">
    <span class="text-gray-700 dark:text-gray-400">price</span>
    <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 ">
      <%= f.text_field :price, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6" , placeholder: "EUR" %>
    </div>
  </label>
  <label class="block text-sm">
    <span class="text-gray-700 dark:text-gray-400">amount</span>
    <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 ">
      <%= f.text_field :amount, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6" , placeholder: "EUR" %>
    </div>
  </label>
  <label class="block text-sm">
    <span class="text-gray-700 dark:text-gray-400">full_price</span>
    <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 ">
      <%= f.text_field :full_price, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6" , placeholder: "EUR" %>
    </div>
  </label>
  <label class="block text-sm">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              items_path, :class => 'btn btn-default' %>
  </label>
<% end %>

app/views/items/edit.html.erb
<h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
  Edit Item
</h2>

<div class="px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800">
  <%= render 'form' %>
</div>

app/views/items/index.html.erb
<h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
  Items
</h2>

<%= link_to "New", new_item_path %>

<div class="grid gap-6 mb-8 md:grid-cols-2 xl:grid-cols-4">
  <div id="area-example"></div>
</div>

<div class="w-full mb-8 overflow-hidden rounded-lg shadow-xs">
  <div class="w-full overflow-x-auto">
    <table class="w-full whitespace-no-wrap">
      <thead>
        <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
          <th class="px-4 py-3">ID</th>
          <th class="px-4 py-3">product_id</th>
          <th class="px-4 py-3">order_id</th>
          <th class="px-4 py-3">price</th>
          <th class="px-4 py-3">amount</th>
          <th class="px-4 py-3">full_price</th>
          <th class="px-4 py-3">Date</th>
          <th class="px-4 py-3">Actions</th>
        </tr>
      </thead>
      <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
        <% @items.each do |item| %>
          <tr class="text-gray-700 dark:text-gray-400">
            <td class="px-4 py-3 text-sm"><%= link_to item.id, item_path(item) %></td>
            <td class="px-4 py-3 text-sm"<%= link_to item.product.name, product_path(item.product) if item.product  %></td>
            <td class="px-4 py-3 text-sm"><%= item.order_id %></td>
            <td class="px-4 py-3 text-sm"><%= item.price %></td>
            <td class="px-4 py-3 text-sm"><%= item.amount %></td>
            <td class="px-4 py-3 text-sm"><%= item.full_price %></td>
            <td class="px-4 py-3 text-sm"><%=l item.created_at %></td>
            <td class="px-4 py-3 text-sm">
              <div class="flex items-center space-x-4 text-sm">
                <%= link_to "Edit",
                            edit_item_path(item), :class => "flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray" %>

                            <%= link_to "Destroy",
                                        item_path(item),
                                        :method => :delete,
                                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                                        :class => "flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<script>
  Morris.Area({
    element: 'area-example',
    data: [
      <% @items.each do |item|%>
      { y: '<%= item.created_at.to_s %>', a: <%= item.full_price %>},
      <% end %>
    ],
    xkey: 'y',
    ykeys: ['a'],
    labels: ['Unit Price']
  });
</script>

app/views/items/new.html.erb
<h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
  New Item
</h2>

<div class="px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800">
  <%= render 'form' %>
</div>

app/views/items/show.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:product_id) %>:</strong></dt>
  <dd><%= @item.product_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:order_id) %>:</strong></dt>
  <dd><%= @item.order_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @item.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @item.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:full_price) %>:</strong></dt>
  <dd><%= @item.full_price %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              items_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_item_path(@item), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              item_path(@item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>