config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "orders#index"

  resources :products
  resources :orders
  resources :items
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: [ :show, :edit, :update, :destroy ]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :ean, :type_id)
    end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <label class="block text-sm">
    <span class="text-gray-700 dark:text-gray-400">name</span>
    <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 ">
      <%= f.text_field :name, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6" , placeholder: "EUR" %>
    </div>
  </label>
  <label class="block text-sm">
    <span class="text-gray-700 dark:text-gray-400">ean</span>
    <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 ">
      <%= f.text_field :ean, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6" , placeholder: "EUR" %>
    </div>
  </label>
  <label class="block text-sm">
    <span class="text-gray-700 dark:text-gray-400">type_id</span>
    <div class="flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 ">
      <%= f.text_field :type_id, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6" , placeholder: "EUR" %>
    </div>
  </label>
  <label class="block text-sm">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              products_path, :class => 'btn btn-default' %>
  </label>
<% end %>

app/views/products/edit.html.erb
<h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
  Edit Product
</h2>

<div class="px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800">
  <%= render 'form' %>
</div>

app/views/products/index.html.erb
<h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
  Products
</h2>

<%= link_to "New", new_product_path %>

<div class="grid gap-6 mb-8 md:grid-cols-2 xl:grid-cols-4">
  <div id="area-example"></div>
</div>

<div class="w-full mb-8 overflow-hidden rounded-lg shadow-xs">
  <div class="w-full overflow-x-auto">
    <table class="w-full whitespace-no-wrap">
      <thead>
        <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
          <th class="px-4 py-3">ID</th>
          <th class="px-4 py-3">name</th>
          <th class="px-4 py-3">ean</th>
          <th class="px-4 py-3">type_id</th>
          <th class="px-4 py-3">created_at</th>
          <th class="px-4 py-3">items</th>
          <th class="px-4 py-3">Actions</th>
        </tr>
      </thead>
      <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
        <% @products.each do |product| %>
          <tr class="text-gray-700 dark:text-gray-400">
            <td class="px-4 py-3 text-sm"><%= link_to product.id, product_path(product) %></td>
            <td class="px-4 py-3 text-sm"><%=  product.name %></td>
            <td class="px-4 py-3 text-sm"><%= product.ean %></td>
            <td class="px-4 py-3 text-sm"><%= product.type_id %></td>
            <td class="px-4 py-3 text-sm"><%= product.created_at %></td>
            <td class="px-4 py-3 text-sm"><%= link_to product.items.count, items_path(:product_id=>product.id) %></td>
            <td class="px-4 py-3 text-sm">
              <div class="flex items-center space-x-4 text-sm">
                <%= link_to "Edit",
                            edit_product_path(product), :class => "flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray" %>

                            <%= link_to "Destroy",
                                        product_path(product),
                                        :method => :delete,
                                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                                        :class => "flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/products/new.html.erb
<h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
  New Product
</h2>

<div class="px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800">
  <%= render 'form' %>
</div>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ean) %>:</strong></dt>
  <dd><%= @product.ean %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type_id) %>:</strong></dt>
  <dd><%= @product.type_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>


<br>
<br>

<div id="area-example"></div>
<script>
  Morris.Area({
    element: 'area-example',
    data: [
      <% for item in @product.items%>
      { y: '<%=item.created_at.to_s(:db)%>', a: <%=item.full_price%>},
      <% end %>
    ],
    xkey: 'y',
    ykeys: ['a'],
    labels: ['Unit Price']
  });
</script>